version: '1'

volumes:
  oracle_data:
    driver: local

services:
  oracle-db:
    container_name: smarthost-db
    image: gvenzl/oracle-free:23.3
    restart: unless-stopped
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_ALLOW_REMOTE=true